name: Pengenalan GitHub Actions
run-name: ${{ github.actor }} sedang mencoba GitHub Actions 🔥
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: echo "🎉 Job ini otomatis dijalankan oleh ${{ github.event_name }}."
      - run: echo "Dijalankan di server ${{ runner.os }}."
      - run: echo "Nama branch ${{ github.ref }}."
      - run: echo "Nama reponya ${{ github.repository }}."

      - name: Daftar file yang ada di repo
        run: |
          ls -lah ${{ github.workspace }}
